### ISSUE TITLE
Support protocol 7 API changes in the Rust SDK

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-rust-sdk#192]
**Task description**

Integrate node 7 API changes into the Rust SDK and release it.

- [X] Deprecate/remove encrypted transfers
- [ ] Support changes to account cooldown handling and available balance calculation
- [ ] Support changes to baker pool responses.
