### ISSUE TITLE
Node version 8: update Rust SDK

### ISSUE THREAD

**Issue by erasmus** [Concordium/concordium-rust-sdk#216]
Node V8 API changes:

- [x] Add `GetConsensusDetailedStatus` endpoint for querying detailed consensus status information. Closed by #226.
- [X] Add `GetScheduledReleaseAccounts` endpoint for querying the list of accounts that have scheduled releases. Closed by #218.
- [X] Add `GetCooldownAccounts`, `GetPreCooldownAccounts` and `GetPrePreCooldownAccounts `endpoints for querying the lists of accounts that have pending cooldowns in protocol version 7 onwards. Closed by #218.
- [X] Add `parameter` field to `ContractInitializedEvent` containing the parameter passed to the contract initializer. Closed by #218.

Protocol 8 specific changes ([RUS-202](https://linear.app/concordium/issue/RUS-202/rust-sdk-support-for-inactive-validators-p8)):

* Added `BakerSuspended`, `BakerResumed` message types and corresponding events.
* Add chain parameter V3 with new `ValidatorScoreParameters` parameters.
* Add `is_suspended` field to `AccountStakingInfo::Baker`.
